from pathlib import Path

import pandas as pd
import plotly.graph_objects as go
import streamlit as st
from sklearn.ensemble import RandomForestClassifier

# To Run, type in Terminal: streamlit run app.py

# --- Setup Page Configuration ---
st.set_page_config(page_title="🌍 Supply Chain Risk Forecaster...", layout="centered")


# --- ML Model Training (Cached for Performance) ---
@st.cache_resource(show_spinner="Training model on real data...")
def load_and_train_model():
    """
    Loads the dataset, prepares the features we want to use in the UI,
    and trains a Random Forest model. Returns the model and expected columns.
    """
    try:
        # # 1. Get the directory where this app.py file lives
        # current_dir = Path(__file__).parent
        #
        # # 2. Join it with the dataset filename
        # file_path = current_dir / 'cleaned_supply_chain_data.csv'
        # file_path = '../data/processed/cleaned_supply_chain_data.csv'
        #
        # # 3. Read the CSV using the bulletproof path
        # df = pd.read_csv(file_path)
        df = pd.read_csv('../data/processed/cleaned_supply_chain_data.csv')

    except FileNotFoundError:
        st.error("Dataset not found!")
        st.stop()

    # Isolate the core features relevant to our UI
    features = ['Geopolitical_Risk_Score', 'Carrier_Reliability_Score', 'Weather_Condition',
                "Lead_Time_Days"]
    X = df[features]
    y = df['Disruption_Occurred']

    # One-hot encode the weather conditions
    X_encoded = pd.get_dummies(X, columns=['Weather_Condition'])

    # Train the Random Forest
    model = RandomForestClassifier(n_estimators=100, max_depth=6, random_state=42)
    model.fit(X_encoded, y)

    return model, X_encoded.columns


# Load model and column structure
rf_model, model_columns = load_and_train_model()


def predict_disruption_probability(geo_risk, weather, reliability, lead_time):
    """
    Formats the user's input to match the training data and returns the ML prediction.
    """
    # Initialize a dictionary with numerical inputs
    input_data = {
        'Geopolitical_Risk_Score': [geo_risk],
        'Carrier_Reliability_Score': [reliability],
        'Lead_Time_Days': [lead_time]
    }

    # Handle dynamic Weather columns generated by get_dummies
    for col in model_columns:
        if col.startswith('Weather_Condition_'):
            weather_type = col.replace('Weather_Condition_', '')
            input_data[col] = [1 if weather == weather_type else 0]

    # Convert to DataFrame ensuring column order exactly matches training data
    input_df = pd.DataFrame(input_data)[model_columns]

    # Get Probability of Class 1 (Disruption Occurred)
    prob = rf_model.predict_proba(input_df)[0][1]
    return prob


# --- UI Header ---
st.title("🌍 Supply Chain Risk Forecaster")
st.markdown(
    "This tool is powered by a **Random Forest** model trained on the historical supply chain dataset, capturing true non-linear risks. Demonstrates how compounding variables—like moderate weather, geopolitical tension, carrier reliability and economic pressures—interact to cause critical supply chain disruptions.")
st.divider()

# --- Input Section ---
col1, col2 = st.columns((1, 1))

with col1:
    st.subheader("Risk Parameters",
                 help="Adjust these parameters to simulate the impact of different environmental and political factors.")

    weather_options = st.selectbox("🌤️ Weather Condition", ["☀️ Clear", "🌫️ Fog", "🌧️ Rain", "⛈️ Storm", "🌀 Hurricane"],
                                   index=2)

    # Remove icons from the dropdown values for model input
    weather_mapping = {
        "☀️ Clear": "Clear",
        "🌫️ Fog": "Fog",
        "🌧️ Rain": "Rain",
        "⛈️ Storm": "Storm",
        "🌀 Hurricane": "Hurricane"
    }
    weather = weather_mapping[weather_options]

    lead_time = st.slider("⏱️ Expected Lead Time (Days)", 1, 60, 12, 1, help="Estimated days until delivery.")

    geo_risk = st.slider("🚨 Geopolitical Risk Score", min_value=0.0, max_value=10.0, value=7.0, step=0.1,
                         help="0 = Perfectly stable, 10 = Active conflict/embargoes")

    reliability = st.slider("🚢 Carrier Reliability", min_value=0.1, max_value=1.0, value=0.65, step=0.01,
                            help="1.0 = Perfect track record, 0.1 = Extremely unreliable")

# --- Processing via ML Model ---
prob = predict_disruption_probability(geo_risk, weather, reliability, lead_time)
prob_percent = prob * 100

# Assign color based on severity
if prob_percent < 35:
    gauge_color = "green"
    status_text = "Low Risk"
elif prob_percent < 65:
    gauge_color = "orange"
    status_text = "Elevated Risk"
else:
    gauge_color = "red"
    status_text = "Severe Disruption Risk"

# --- Output Section ---
with col2:
    st.subheader("Estimated Risk", help="Probability of disruption (out of 100%)", text_alignment="center")

    # Plotly Gauge Chart
    fig = go.Figure(go.Indicator(
        mode="gauge+number",
        value=prob_percent,
        number={'suffix': "%", 'valueformat': ".1f"},
        domain={'x': [0, 1], 'y': [0, 1]},
        title={'text': status_text, 'font': {'size': 20}},
        gauge={
            'axis': {'range': [0, 100], 'tickwidth': 1, 'tickcolor': "darkblue"},
            'bar': {'color': gauge_color},
            'bgcolor': "white",
            'borderwidth': 2,
            'bordercolor': "gray",
            'steps': [
                {'range': [0, 35], 'color': 'rgba(0, 255, 0, 0.1)'},
                {'range': [35, 65], 'color': 'rgba(255, 165, 0, 0.1)'},
                {'range': [65, 100], 'color': 'rgba(255, 0, 0, 0.1)'}],
        }
    ))

    fig.update_layout(height=300, margin=dict(l=20, r=20, t=40, b=20))
    st.plotly_chart(fig, use_container_width=True)

# --- Dynamic Diagnostics (Based on inputs) ---
st.divider()
st.subheader("Risk Assessment & Strategy", help="Strategic outlook, threat landscape, and actionable insights")

# 1. Determine Assessment and Action based on conditions
if prob_percent > 65:
    assessment_type = "error"
    if weather in ["Hurricane", "Storm"] and lead_time < 14:
        assessment_msg = f"⚠️ **CRITICAL BOTTLENECK:** Severe {weather.lower()} conditions combined with a tight lead time of {lead_time} days leave virtually no buffer for transit delays."
        action_msg = "Immediately evaluate alternative routing, expedite secondary shipments, or alert downstream stakeholders to impending shortages."
    elif geo_risk > 7.5 and lead_time > 30:
        assessment_msg = f"⚠️ **PROLONGED EXPOSURE RISK:** An extended transit time ({lead_time} days) through highly volatile geopolitical environments (Risk Score: {geo_risk}) significantly amplifies the threat of sudden border closures, embargoes, or kinetic disruptions."
        action_msg = "Secure secondary sourcing and temporarily increase localized safety stock."
    else:
        assessment_msg = "⚠️ **HIGH DISRUPTION PROBABILITY:** Compounding vulnerabilities across environmental, regional, and carrier dimensions indicate a severe risk to the delivery timeline."
        action_msg = "Initiate comprehensive contingency plans and establish high-frequency tracking protocols."

elif prob_percent > 35:
    assessment_type = "warning"
    if reliability < 0.6:
        assessment_msg = f"🔔 **CARRIER VULNERABILITY:** The selected carrier's sub-optimal reliability score ({reliability}) introduces a fragile link into the fulfillment cycle."
        action_msg = "Prepare backup logistics providers for future nodes and audit service-level agreements for delay penalties."
    elif geo_risk > 6.0:
        assessment_msg = f"🏛️ **REGIONAL FRICTION:** Heightened geopolitical tension is introducing systemic drag on regional transit networks."
        action_msg = "Monitor trade compliance alerts closely and ensure all customs and border documentation is preemptively cleared to avoid administrative holds."
    else:
        assessment_msg = "🔔 **ELEVATED OPERATIONAL FRICTION:** Moderate systemic pressures exist across the route. While outright failure isn't imminent, cumulative minor delays are probable."
        action_msg = "Review current inventory buffers and proactively synchronize expectations with dependent supply chain tiers."

else:
    assessment_type = "success"
    assessment_msg = "✅ **OPTIMAL ROUTING:** Current parameters indicate a highly resilient logistical profile. Stable geopolitical factors, reliable carrier history, and manageable weather patterns strongly support an on-time delivery schedule."
    action_msg = "Proceed with standard automated tracking and fulfillment pipelines."


# 2. Render the UI (Visual Separation)
if assessment_type == "error":
    st.error(assessment_msg)
elif assessment_type == "warning":
    st.warning(assessment_msg)
else:
    st.success(assessment_msg)

# Use an info box for a clean, visually distinct action item
st.info(f"🎯 **Recommended Action:** {action_msg}")